### ISSUE TITLE
Make "no timestamp" error configurable

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma-requirejs#6]
For instance when loading files through proxy, there's no timestamp and it's perfectly valid use case.

Maybe something like:
```js
client: {
  requireJsShowNoTimestampsError: false
}
```

**Comment by asgoth** [comment]
I did the same as @indrajitdas85, but with a different `baseUrl`:

    baseUrl: '/base/js'

Note the "/" at the start. Without it, there timestamp errors pop up.

This way, it's easier to use an other port.

**Comment by sstadt** [comment]
I had the same issue recently and for me there was a combination of an assumption based on a lack of understanding that /base is a keyword for karma. I kept interpreting /base/js as an indication that /base should be replaced with the path to where my js file lives.

The solution for me was very much inline with what others have mentioned above, but had to be combined with knowing that /base will be properly interpreted by karma as the base directory for my project (please correct me if my explanation is a little off on this).

So for my project (written in sails.js, which puts js files in assets/js) was as follows...

karma.conf.js
```
...

baseUrl: '/base',

...
```

test-main.js
```
var tests = [];

for (var file in window.__karma__.files) {
  if (window.__karma__.files.hasOwnProperty(file)) {
    if (/Spec\.js$/.test(file)) {
      tests.push(file);
    }
  }
}

requirejs.config({
  baseUrl: '/base/assets/js',
  deps: tests,
  callback: window.__karma__.start
});
```

And, for the sake of being comprehensive, I'm using my apps existing requirejs config to avoid repeating my fairly lengthy foundation 5 shims.

karma.conf.js
```
...

files: [
  {pattern: 'assets/js/test-main.js', included: true},
  {pattern: 'assets/js/lib/config.js', included: true},
  {pattern: 'assets/js/**/*.js', included: false}
],

...
```

Full project code: https://github.com/sstadt/d20-character-tracker

**Comment by jacksonrayhamilton** [comment]
I'd like to submit a fix for this. Should we add support for `client.requireJsShowNoTimestampsError`? Also, it might be nice to allow specifying a predicate function for this option, so you can detect proxy URLs and still get the error when it'd be useful.

**Comment by jacksonrayhamilton** [comment]
Scratch the idea of a predicate function; turns out [the client configuration is serialized](https://github.com/karma-runner/karma/blob/2d51260f06308a7a66acff0c60cdf51636d33e7d/lib/middleware/karma.js#L200), so that won't work.

For my purposes, next best solution would be the ability to specify a regular expression matching the files that can trigger the error. I wanted to suppress this message for requests under `/base/app/node_modules`, which I was serving via middleware, so with the ability to specify a RegExp string I can now ignore the error for those files:

```js
client: {
  requireJsShowNoTimestampsError: '^(?!.*(^/base/app/node_modules/))'
}
```

I think I've implemented the option [here](https://github.com/jacksonrayhamilton/karma-requirejs/compare/v1.0.0...7918c8a), and can submit a PR if the maintainer wants it.
